"""City anchors shared by fixture generation and geographic validation."""

# Curated city anchors: state IDs refer to the bundled reference snapshot.
SEEDED_CITIES = [
    # United States (country_id = 233)
    {
        "city_name": "San Jose",
        "state_code": "CA",
        "state_id": "233.7",
        "lat": 37.3382,
        "lon": -121.8863,
        "tz": "America/Los_Angeles",
        "zip": "95112",
    },
    {
        "city_name": "San Francisco",
        "state_code": "CA",
        "state_id": "233.7",
        "lat": 37.7749,
        "lon": -122.4194,
        "tz": "America/Los_Angeles",
        "zip": "94102",
    },
    {
        "city_name": "Los Angeles",
        "state_code": "CA",
        "state_id": "233.7",
        "lat": 34.0522,
        "lon": -118.2437,
        "tz": "America/Los_Angeles",
        "zip": "90001",
    },
    {
        "city_name": "San Diego",
        "state_code": "CA",
        "state_id": "233.7",
        "lat": 32.7157,
        "lon": -117.1611,
        "tz": "America/Los_Angeles",
        "zip": "92101",
    },
    {
        "city_name": "Sacramento",
        "state_code": "CA",
        "state_id": "233.7",
        "lat": 38.5816,
        "lon": -121.4944,
        "tz": "America/Los_Angeles",
        "zip": "95814",
    },
    {
        "city_name": "New York",
        "state_code": "NY",
        "state_id": "233.42",
        "lat": 40.7128,
        "lon": -74.0060,
        "tz": "America/New_York",
        "zip": "10001",
    },
    {
        "city_name": "Buffalo",
        "state_code": "NY",
        "state_id": "233.42",
        "lat": 42.8864,
        "lon": -78.8784,
        "tz": "America/New_York",
        "zip": "14201",
    },
    {
        "city_name": "Albany",
        "state_code": "NY",
        "state_id": "233.42",
        "lat": 42.6526,
        "lon": -73.7562,
        "tz": "America/New_York",
        "zip": "12201",
    },
    {
        "city_name": "Austin",
        "state_code": "TX",
        "state_id": "233.56",
        "lat": 30.2672,
        "lon": -97.7431,
        "tz": "America/Chicago",
        "zip": "73301",
    },
    {
        "city_name": "Houston",
        "state_code": "TX",
        "state_id": "233.56",
        "lat": 29.7604,
        "lon": -95.3698,
        "tz": "America/Chicago",
        "zip": "77001",
    },
    {
        "city_name": "Dallas",
        "state_code": "TX",
        "state_id": "233.56",
        "lat": 32.7767,
        "lon": -96.7970,
        "tz": "America/Chicago",
        "zip": "75201",
    },
    {
        "city_name": "San Antonio",
        "state_code": "TX",
        "state_id": "233.56",
        "lat": 29.4241,
        "lon": -98.4936,
        "tz": "America/Chicago",
        "zip": "78201",
    },
    {
        "city_name": "Seattle",
        "state_code": "WA",
        "state_id": "233.63",
        "lat": 47.6062,
        "lon": -122.3321,
        "tz": "America/Los_Angeles",
        "zip": "98101",
    },
    {
        "city_name": "Spokane",
        "state_code": "WA",
        "state_id": "233.63",
        "lat": 47.6588,
        "lon": -117.4260,
        "tz": "America/Los_Angeles",
        "zip": "99201",
    },
    {
        "city_name": "Chicago",
        "state_code": "IL",
        "state_id": "233.18",
        "lat": 41.8781,
        "lon": -87.6298,
        "tz": "America/Chicago",
        "zip": "60601",
    },
    {
        "city_name": "Miami",
        "state_code": "FL",
        "state_id": "233.12",
        "lat": 25.7617,
        "lon": -80.1918,
        "tz": "America/New_York",
        "zip": "33101",
    },
    {
        "city_name": "Orlando",
        "state_code": "FL",
        "state_id": "233.12",
        "lat": 28.5383,
        "lon": -81.3792,
        "tz": "America/New_York",
        "zip": "32801",
    },
    {
        "city_name": "Tampa",
        "state_code": "FL",
        "state_id": "233.12",
        "lat": 27.9506,
        "lon": -82.4572,
        "tz": "America/New_York",
        "zip": "33601",
    },
    {
        "city_name": "Richmond",
        "state_code": "VA",
        "state_id": "233.61",
        "lat": 37.5407,
        "lon": -77.4360,
        "tz": "America/New_York",
        "zip": "23219",
    },
    {
        "city_name": "Virginia Beach",
        "state_code": "VA",
        "state_id": "233.61",
        "lat": 36.8529,
        "lon": -75.9780,
        "tz": "America/New_York",
        "zip": "23450",
    },
    {
        "city_name": "Atlanta",
        "state_code": "GA",
        "state_id": "233.13",
        "lat": 33.7490,
        "lon": -84.3880,
        "tz": "America/New_York",
        "zip": "30301",
    },
    {
        "city_name": "Boston",
        "state_code": "MA",
        "state_id": "233.29",
        "lat": 42.3601,
        "lon": -71.0589,
        "tz": "America/New_York",
        "zip": "02108",
    },
    {
        "city_name": "Denver",
        "state_code": "CO",
        "state_id": "233.8",
        "lat": 39.7392,
        "lon": -104.9903,
        "tz": "America/Denver",
        "zip": "80201",
    },
    {
        "city_name": "Phoenix",
        "state_code": "AZ",
        "state_id": "233.4",
        "lat": 33.4484,
        "lon": -112.0740,
        "tz": "America/Denver",
        "zip": "85001",
    },
    {
        "city_name": "Portland",
        "state_code": "OR",
        "state_id": "233.48",
        "lat": 45.5152,
        "lon": -122.6784,
        "tz": "America/Los_Angeles",
        "zip": "97201",
    },
    {
        "city_name": "Philadelphia",
        "state_code": "PA",
        "state_id": "233.50",
        "lat": 39.9526,
        "lon": -75.1652,
        "tz": "America/New_York",
        "zip": "19101",
    },
    {
        "city_name": "Charlotte",
        "state_code": "NC",
        "state_id": "233.43",
        "lat": 35.2271,
        "lon": -80.8431,
        "tz": "America/New_York",
        "zip": "28201",
    },
    {
        "city_name": "Raleigh",
        "state_code": "NC",
        "state_id": "233.43",
        "lat": 35.7796,
        "lon": -78.6382,
        "tz": "America/New_York",
        "zip": "27601",
    },
    {
        "city_name": "Minneapolis",
        "state_code": "MN",
        "state_id": "233.32",
        "lat": 44.9778,
        "lon": -93.2650,
        "tz": "America/Chicago",
        "zip": "55401",
    },
    {
        "city_name": "Detroit",
        "state_code": "MI",
        "state_id": "233.30",
        "lat": 42.3314,
        "lon": -83.0458,
        "tz": "America/Detroit",
        "zip": "48201",
    },
    # India (country_id = 101)
    {
        "city_name": "Mumbai",
        "state_code": "MH",
        "state_id": "101.21",
        "lat": 19.0760,
        "lon": 72.8777,
        "tz": "Asia/Kolkata",
        "zip": "400001",
    },
    {
        "city_name": "Pune",
        "state_code": "MH",
        "state_id": "101.21",
        "lat": 18.5204,
        "lon": 73.8567,
        "tz": "Asia/Kolkata",
        "zip": "411001",
    },
    {
        "city_name": "Nagpur",
        "state_code": "MH",
        "state_id": "101.21",
        "lat": 21.1458,
        "lon": 79.0882,
        "tz": "Asia/Kolkata",
        "zip": "440001",
    },
    {
        "city_name": "Bengaluru",
        "state_code": "KA",
        "state_id": "101.16",
        "lat": 12.9716,
        "lon": 77.5946,
        "tz": "Asia/Kolkata",
        "zip": "560001",
    },
    {
        "city_name": "Mysuru",
        "state_code": "KA",
        "state_id": "101.16",
        "lat": 12.2958,
        "lon": 76.6394,
        "tz": "Asia/Kolkata",
        "zip": "570001",
    },
    {
        "city_name": "Hyderabad",
        "state_code": "TG",
        "state_id": "101.32",
        "lat": 17.3850,
        "lon": 78.4867,
        "tz": "Asia/Kolkata",
        "zip": "500001",
    },
    {
        "city_name": "Chennai",
        "state_code": "TN",
        "state_id": "101.31",
        "lat": 13.0827,
        "lon": 80.2707,
        "tz": "Asia/Kolkata",
        "zip": "600001",
    },
    {
        "city_name": "New Delhi",
        "state_code": "DL",
        "state_id": "101.9",
        "lat": 28.6139,
        "lon": 77.2090,
        "tz": "Asia/Kolkata",
        "zip": "110001",
    },
    {
        "city_name": "Kolkata",
        "state_code": "WB",
        "state_id": "101.36",
        "lat": 22.5726,
        "lon": 88.3639,
        "tz": "Asia/Kolkata",
        "zip": "700001",
    },
    {
        "city_name": "Ahmedabad",
        "state_code": "GJ",
        "state_id": "101.11",
        "lat": 23.0225,
        "lon": 72.5714,
        "tz": "Asia/Kolkata",
        "zip": "380001",
    },
    {
        "city_name": "Jaipur",
        "state_code": "RJ",
        "state_id": "101.29",
        "lat": 26.9124,
        "lon": 75.7873,
        "tz": "Asia/Kolkata",
        "zip": "302001",
    },
    {
        "city_name": "Kochi",
        "state_code": "KL",
        "state_id": "101.17",
        "lat": 9.9312,
        "lon": 76.2673,
        "tz": "Asia/Kolkata",
        "zip": "682001",
    },
    # United Kingdom (country_id = 232)
    {
        "city_name": "London",
        "state_code": "ENG",
        "state_id": "232.88",
        "lat": 51.5074,
        "lon": -0.1278,
        "tz": "Europe/London",
        "zip": "EC1A 1BB",
    },
    {
        "city_name": "Manchester",
        "state_code": "ENG",
        "state_id": "232.88",
        "lat": 53.4808,
        "lon": -2.2426,
        "tz": "Europe/London",
        "zip": "M1 1AE",
    },
    {
        "city_name": "Birmingham",
        "state_code": "ENG",
        "state_id": "232.88",
        "lat": 52.4862,
        "lon": -1.8904,
        "tz": "Europe/London",
        "zip": "B1 1AA",
    },
    {
        "city_name": "Edinburgh",
        "state_code": "SCT",
        "state_id": "232.202",
        "lat": 55.9533,
        "lon": -3.1883,
        "tz": "Europe/London",
        "zip": "EH1 1YZ",
    },
    {
        "city_name": "Glasgow",
        "state_code": "SCT",
        "state_id": "232.202",
        "lat": 55.8642,
        "lon": -4.2518,
        "tz": "Europe/London",
        "zip": "G1 1XQ",
    },
    # Canada (country_id = 39)
    {
        "city_name": "Toronto",
        "state_code": "ON",
        "state_id": "39.9",
        "lat": 43.6532,
        "lon": -79.3832,
        "tz": "America/Toronto",
        "zip": "M5H 2N2",
    },
    {
        "city_name": "Ottawa",
        "state_code": "ON",
        "state_id": "39.9",
        "lat": 45.4215,
        "lon": -75.6972,
        "tz": "America/Toronto",
        "zip": "K1P 1J1",
    },
    {
        "city_name": "Vancouver",
        "state_code": "BC",
        "state_id": "39.2",
        "lat": 49.2827,
        "lon": -123.1207,
        "tz": "America/Vancouver",
        "zip": "V6B 1A1",
    },
    {
        "city_name": "Montreal",
        "state_code": "QC",
        "state_id": "39.11",
        "lat": 45.5017,
        "lon": -73.5673,
        "tz": "America/Toronto",
        "zip": "H2Y 1C6",
    },
    {
        "city_name": "Calgary",
        "state_code": "AB",
        "state_id": "39.1",
        "lat": 51.0447,
        "lon": -114.0719,
        "tz": "America/Edmonton",
        "zip": "T2P 0A1",
    },
    # Germany (country_id = 82 - EU)
    {
        "city_name": "Berlin",
        "state_code": "BE",
        "state_id": "82.3",
        "lat": 52.5200,
        "lon": 13.4050,
        "tz": "Europe/Berlin",
        "zip": "10115",
    },
    {
        "city_name": "Munich",
        "state_code": "BY",
        "state_id": "82.2",
        "lat": 48.1351,
        "lon": 11.5820,
        "tz": "Europe/Berlin",
        "zip": "80331",
    },
    {
        "city_name": "Frankfurt",
        "state_code": "HE",
        "state_id": "82.7",
        "lat": 50.1109,
        "lon": 8.6821,
        "tz": "Europe/Berlin",
        "zip": "60311",
    },
    {
        "city_name": "Hamburg",
        "state_code": "HH",
        "state_id": "82.6",
        "lat": 53.5511,
        "lon": 9.9937,
        "tz": "Europe/Berlin",
        "zip": "20095",
    },
    # France (country_id = 75 - EU)
    {
        "city_name": "Paris",
        "state_code": "IDF",
        "state_id": "75.60",
        "lat": 48.8566,
        "lon": 2.3522,
        "tz": "Europe/Paris",
        "zip": "75001",
    },
    {
        "city_name": "Lyon",
        "state_code": "ARA",
        "state_id": "75.12",
        "lat": 45.7640,
        "lon": 4.8357,
        "tz": "Europe/Paris",
        "zip": "69001",
    },
    {
        "city_name": "Marseille",
        "state_code": "PAC",
        "state_id": "75.96",
        "lat": 43.2965,
        "lon": 5.3698,
        "tz": "Europe/Paris",
        "zip": "13001",
    },
    # Australia (country_id = 14)
    {
        "city_name": "Sydney",
        "state_code": "NSW",
        "state_id": "14.2",
        "lat": -33.8688,
        "lon": 151.2093,
        "tz": "Australia/Sydney",
        "zip": "2000",
    },
    {
        "city_name": "Melbourne",
        "state_code": "VIC",
        "state_id": "14.7",
        "lat": -37.8136,
        "lon": 144.9631,
        "tz": "Australia/Melbourne",
        "zip": "3000",
    },
    {
        "city_name": "Brisbane",
        "state_code": "QLD",
        "state_id": "14.4",
        "lat": -27.4698,
        "lon": 153.0251,
        "tz": "Australia/Brisbane",
        "zip": "4000",
    },
    {
        "city_name": "Perth",
        "state_code": "WA",
        "state_id": "14.8",
        "lat": -31.9505,
        "lon": 115.8605,
        "tz": "Australia/Perth",
        "zip": "6000",
    },
]
